name: Push-Triggers

on:
  push:
    branches:
    - main
    - develop
    - qa-develop
    - 'release-**'
    - inji-sonar-qube-android
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - main
    - develop
    - qa-develop
    - 'release-**'

jobs:
  # build-android:
  #   uses: mosip/kattu/.github/workflows/android-build.yml@master
  #   with:
  #     NODE_VERSION: "16.x"
  #     DEBUG_KEYSTORE_ALIAS: androiddebugkey
  #     SERVICE_LOCATION: '.'
  #     ANDROID_SERVICE_LOCATION: 'android'
  #     BUILD_SCRIPT_LOCATION: 'scripts'
  #     SCRIPT_NAME: './android-build.sh'
  #   secrets:
  #     DEBUG_KEYSTORE_PASSWORD: '${{ secrets.INJI_ANDROID_DEBUG_STOREPASS }}'

  # build-ios:
  #   uses: mosip/kattu/.github/workflows/ios-build.yml@master
  #   with:
  #     NODE_VERSION: "18.x"
  #     SERVICE_LOCATION: '.'
  #     IOS_SERVICE_LOCATION: 'ios'
  #     SCRIPT_NAME: "fastlane ios_app_build"

  sonar-check-on-push:
    name: Sonar check
    if: ${{ github.event_name != 'pull_request' }}
    # needs: [build-android, build-ios]
    uses: tw-mosip/kattu/.github/workflows/npm-sonar-analysis.yml@inji-597-customize-npm-sonar-analysis
    with:
      SERVICE_LOCATION: '.'
      NODE_VERSION: '18.x'
      NPM_BUILD_TYPE: 'BOB'
      SONAR_SOURCES: '.'
      SONAR_TESTS: '.'
      SONAR_EXCLUSIONS: '.github/**, .vscode/**, android/**, assets/**, build/**, ios/**, node_modules/**, scripts/**, **/*.java, **/*.typegen.ts'
      SONAR_ARGS: " -Dsonar.branch.name=${GITHUB_REF_NAME}"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ORG_KEY: ${{ secrets.ORG_KEY }}
      SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}'

  check-sonar-critical-issues:
    needs: sonar-check-on-push
    name: Check critical issues in sonar analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for critical bugs
        run: |
          cd scripts
          BRANCH_NAME=${GITHUB_REF_NAME}
          ./check-sonar-critical-issues.sh BRANCH_NAME
      - uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job,job_name
        env:
          SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}'
