name: Push-Triggers

env:
  backendServiceDefaultUrl: https://api.sandbox.mosip.net

on:
  push:
    branches:
      - main
      - develop
      - demobranch
      - qa-develop
      - 0.9
    tags:
      - '*'
  pull_request: 
    types: [ opened, synchronize ]
    branches:
      - develop
      - 'release-**'
    tags: 
      - '*'

jobs:
  build-android:
    uses: mosip/kattu/.github/workflows/android-build-verify.yml@master
    secrets:
      FIREBASE_SECRET: ${{ secrets.GPG_SECRET }}
      DEBUG_KEYSTORE_PASSWORD: '${{secrets.INJI_ANDROID_DEBUG_STOREPASS}}'
      DEBUG_KEYSTORE_ALIAS: androiddebugkey

  build-ios:
    uses: mosip/kattu/.github/workflows/ios-build-verify.yml@master
    secrets:
      APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
      DEVELOPER_APP_ID: '${{ secrets.IOS_INJI_DEVELOPER_APP_ID }}'
      INJI_IOS_DEVELOPER_APP_IDENTIFIER: '${{ secrets.INJI_IOS_DEVELOPER_APP_IDENTIFIER }}'
      INJI_IOS_DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.INJI_IOS_DEVELOPER_PORTAL_TEAM_ID }}'
      INJI_IOS_FASTLANE_APPLE_ID: '${{ secrets.INJI_IOS_FASTLANE_APPLE_ID }}'
      INJI_IOS_FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.INJI_IOS_FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
      GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
      INJI_IOS_PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.INJI_IOS_PROVISIONING_PROFILE_SPECIFIER }}'
      INJI_IOS_TEMP_KEYCHAIN_PASSWORD: '${{ secrets.INJI_IOS_TEMP_KEYCHAIN_PASSWORD }}'
      INJI_IOS_TEMP_KEYCHAIN_USER: '${{ secrets.INJI_IOS_TEMP_KEYCHAIN_USER }}'
      APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
      APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
      APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'
      MATCH_PASSWORD: '${{ secrets.INJI_IOS_MATCH_PASSWORD }}'
  
  sonar-check:
    if: "${{ contains(github.ref, 'develop') && github.event_name == 'push' }}"
    uses: mosip/kattu/.github/workflows/sonar.yml@master
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_ORGANIZATION: ${{ secrets.ORG_KEY }}