name: UI - Automation
run-name: ${{ inputs.runName }}

on:
  workflow_dispatch:
    inputs:
      runName:
        description: 'Run name'
        required: true
        default: 'Device-pool/Test-name/Env'
        type: string
      buildFor:
        description: 'Build'
        required: true
        default: 'Both[Android and IOS]'
        type: choice
        options:
          - Both[Android and IOS]
          - Android
          - IOS
      testType:
        description: 'Sanity/Regression'
        required: true
        default: 'sanity'
        type: choice
        options:
          - sanity
          - regression
      backendServiceUrl:
        description: 'Mimoto and Esignet backend service URL'
        required: true
        default: 'https://api.sandbox.mosip.net'
        type: string

jobs:
  android-ui-automation:
    if: ${{ github.event.inputs.buildFor == 'Both[Android and IOS]' || github.event.inputs.buildFor == 'Android'}}
    name: Trigger android run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache npm dependencies
        uses: actions/cache@v3.3.1
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
    
      - name: Install npm dependencies
        run: |
          npm ci

      - name: Generate Android keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > release.keystore.b64
          base64 -d -i release.keystore.b64 > android/app/release.keystore
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.INJI_ANDROID_RELEASE_KEYSTORE }}

      - name: Create Android Build
        run: |
          npx jetify
          cd android
          ./gradlew :app:assembleResidentappRelease
        env:
          MIMOTO_HOST: ${{ github.event.inputs.backendServiceUrl }}
          ESIGNET_HOST: ${{ github.event.inputs.backendServiceUrl }}
          APPLICATION_THEME: 'orange'
          CREDENTIAL_REGISTRY_EDIT: 'false'
          RELEASE_KEYSTORE_ALIAS: 'androidreleasekey'
          RELEASE_KEYSTORE_PASSWORD: "${{ secrets.INJI_ANDROID_RELEASE_STOREPASS }}"

      - name: Configure AWS CLI 
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_DEVICE_FARM_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_DEVICE_FARM_SECRET_KEY }}
          aws configure set region us-west-2

      - name: Configure xml file
        run: |
          cd injitest/src/main/resources/
          cat androidSanity.txt > testng.xml
          cd ../../../
          mvn clean package -DskipTests=true
        
      - name: Create test package upload
        uses: realm/aws-devicefarm/create-upload@v1
        id: test-package
        with:
          project_arn: arn:aws:devicefarm:us-west-2:931337674770:project:b356580b-c561-4fd2-bfdf-8993aebafc5a
          name: Android-test
          type: APPIUM_JAVA_TESTNG_TEST_PACKAGE

      - name: Upload test package
        run: |
          curl -T ../../injitest/target/zip-with-dependencies.zip '${{ steps.test-package.outputs.url }}'

      - name: Create app upload
        uses: realm/aws-devicefarm/create-upload@v1
        id: app-upload
        with:
          project_arn: arn:aws:devicefarm:us-west-2:931337674770:project:b356580b-c561-4fd2-bfdf-8993aebafc5a
          name: Inji_universal.apk
          type: ANDROID_APP

      - name: Upload test package
        run: |
          curl -T ../../android/app/build/outputs/apk/residentapp/Inji_universal.apk '${{ steps.app-upload.outputs.url }}'

      - name: Schedule a test run
        uses: realm/aws-devicefarm/schedule-run@v1
        with:
          name: Test-Run
          project_arn: arn:aws:devicefarm:us-west-2:931337674770:project:b356580b-c561-4fd2-bfdf-8993aebafc5a
          device_pool_arn: arn:aws:devicefarm:us-west-2:931337674770:devicepool:b356580b-c561-4fd2-bfdf-8993aebafc5a/90a0ea5c-bbff-449a-8ea4-5a6179fdb05c
          app_arn: ${{ steps.app-upload.outputs.arn }}
          test_type: APPIUM_JAVA_TESTNG
          test_package_arn: ${{ steps.test-package.outputs.arn }}
          test_spec_arn: arn:aws:devicefarm:us-west-2::upload:100e31e8-12ac-11e9-ab14-d663b5a4a910
          
      # - name: Upload Artifact to Actions
      #   uses: actions/upload-artifact@v3.1.1
      #   with:
      #     name: Automation Artifacts
      #     path: injitest/scripts/ui_automation/artifacts/
      #     retention-days: 5
      
      # - name: Update slack channel
      #   if: always()
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,author,commit,workflow,job
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}

  ios-ui-automation:
    if: ${{ github.event.inputs.buildFor == 'Both[Android and IOS]' || github.event.inputs.buildFor == 'IOS'}}
    name: Trigger ios run
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache npm dependencies
        uses: actions/cache@v3.3.1
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
    
      - name: Install npm dependencies
        run: |
          npm ci

      - name: Create iOS Build
        run: |
          cd ios
          pod install && pod install
          fastlane ios_ui_automation_build 
        env:
          MIMOTO_HOST: ${{ github.event.inputs.backendServiceUrl }}
          ESIGNET_HOST: ${{ github.event.inputs.backendServiceUrl }}
          APPLICATION_THEME: 'orange'
          APP_FLAVOR: 'residentapp'
          CREDENTIAL_REGISTRY_EDIT: 'false'
          INJI_IOS_TEMP_KEYCHAIN_PASSWORD: '${{ secrets.INJI_IOS_TEMP_KEYCHAIN_PASSWORD }}'
          INJI_IOS_TEMP_KEYCHAIN_USER: '${{ secrets.INJI_IOS_TEMP_KEYCHAIN_USER }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'

      - name: Configure AWS CLI 
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_DEVICE_FARM_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_DEVICE_FARM_SECRET_KEY }}
          aws configure set region us-west-2

      - name: IOS - Automation
        run: |
          cd injitest/scripts/ui_automation
          RUN_ARN=$(./automation_trigger.sh "IOS" "$RUN_NAME" "$TEST_TYPE")
          echo "The Run ARN is $RUN_ARN"
        env:
          RUN_NAME: ${{ github.event.inputs.runName }}
          TEST_TYPE: ${{ github.event.inputs.testType }}
      
      # - name: Artifacts download
      #   id: artifact-download
      #   run: |
      #     cd injitest/scripts/ui_automation
      #     ./download_artifacts.sh "${{ steps.android-run.outputs.run_arn }}" "Android"

      # - name: Upload Artifact to Actions
      #   uses: actions/upload-artifact@v3.1.1
      #   with:
      #     name: Automation Artifacts
      #     path: injitest/scripts/ui_automation/artifacts/
      #     retention-days: 5
      
      # - name: Update slack channel
      #   if: always()
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,author,commit,workflow,job
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
